export const totalBanner = document.getElementById('total_banner')
export const totalExpense = document.getElementById('total_expense')
export const totalIncome = document.getElementById('total_income')
export const addItemForm = document.getElementById('add_item_form')
export const editItemForm = document.getElementById('edit_item_form')
export const dataTableBody = document.getElementById('data_table_body')
export const filterForm = document.getElementById('filter_form')
export const removeFiltersButton = document.getElementById('remove_filters_button')
export const limitsForm = document.getElementById('limits_form')
export const alerts = document.getElementById('alerts')
export const AmountdateInput = document.getElementById('amount_date_form')
export const monthlychart = document.getElementById('monthlychart')

